# safelist
branches:
    only:
        - /.*/
matrix:
    fast_finish: true
    include:
        -   language: python
            python: 3.6
            dist: xenial
            before_cache:
            cache:
            before_install:
            script: |
                bash .ci/ci_check_commit.sh

        -   language: java
            jdk: openjdk8
            os: linux
            dist: xenial
            sudo: required

        -   language: java
            jdk: openjdk9
            os: linux
            dist: xenial
            sudo: required

        -   language: java
            jdk: openjdk10
            os: linux
            dist: xenial
            sudo: required

        -   language: java
            jdk: openjdk11
            os: linux
            dist: xenial
            sudo: required

        # - language: java
        #   jdk: openjdk11
        #   os: osx
        #   before_install:
        #     - brew install gradle && gradle wrapper

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
before_install:
    - gradle wrapper

addons:
    sonarcloud:
        organization: "shareong"
        token: "ExTiFppy7pX7RYAjYbYNuT15uqZl88EychsyYFfSPprGkjF/bmWoL3QEJsYTw8nz36x5DsilJ5n30MKpAuVqCBn0PxwqqD0FzUbD9U45vOslOs3WKwD9jVfY6natxL1yA0dcas/rOEZRx4QiwvDd8vlf5zcAaJMRye52nFw/RAa+6t9sHYMuCkWaPkPbgOA3vOkbU1NnzOUQbkCuTcozgCGquOVCrqOBJEWNw6xCHlmtRiaTNcqH44syrvSKDur9M8P2rXpsLhTNfSv1RMHXL6gqm00R5+NwyJ9mFrS3nDK2q95NSLJRKHuYoN82qUxuvLwigg6NkEV+91D3aIhIf50K3/ntwklcpXC6dtgMzcCxzMKulFsRncsFJm0HnTio5UQ+OxzrIX4UKF452deZjsyvk0yHVxmJM1DzBgNCJG9aGWAgXJh5hqgd+uYBTEJYhzPgDUm3bgZv+gtYwW6menGcE9LgG0e0FaIV3KtvkcAzbKU5+5la7oJVsAhoS+imWQJ+dXvmHuWCzIPyYUl/+UDzFX8jGbxhTPlIADcXB8yRvABhBHUoZ/iZcAKFGuyAZz+Nj01S9YqaLYtR58DTkArWP/g4uJwm1SG3PMcR4JnhxxcJb+Woivx3N/2sTJqwc2CF+LS6ch2AfesBHuvLpjoKvMxA9ZW27sEmJ36STXc="
script: |
    ./gradlew sonarqube && bash .ci/ci_check.sh


after_success:
    - bash <(curl -s https://codecov.io/bash)